### PR TITLE
Update README.Rmd

### PR DESCRIPTION
**Pull request by sketchkey**
"key" argument missing for get_vessel_info & get_event( doesn't work for me without it) — thanks for making the package!!

### CODE REVIEW

**Comment by tclavelle** [comment]
Hi @sketchkey, thanks for posting an issue! For consistency, we should probably include the `key` argument in all examples. Most functions have a default of `key = gfw_auth()`, however, so they should work without specifying `key` so long as you've added your API token to your `.Renviron` file as described in the [Authorization section](https://github.com/GlobalFishingWatch/gfwr#authorization) of the README. Did you do that?

**Review by tclavelle — APPROVED** [review]

**Comment by sketchkey** [comment]
> Hi @sketchkey, thanks for posting an issue! For consistency, we should probably include the `key` argument in all examples. Most functions have a default of `key = gfw_auth()`, however, so they should work without specifying `key` so long as you've added your API token to your `.Renviron` file as described in the [Authorization section](https://github.com/GlobalFishingWatch/gfwr#authorization) of the README. Did you do that?

Completely agree with the consistency idea — I have since added the API token to .Renviron (I was just being lazy when initially playing around with it 😅). Again, this package is awesome and will definitely be using/recommending this to folks for future projects!

**Comment by tclavelle** [comment]
@sketchkey Cool, just making sure it worked in that context. Thanks for the PR and glad you're finding the package useful!

**Comment by sketchkey** [comment]
> Hi @sketchkey, thanks for posting an issue! For consistency, we should probably include the `key` argument in all examples. Most functions have a default of `key = gfw_auth()`, however, so they should work without specifying `key` so long as you've added your API token to your `.Renviron` file as described in the [Authorization section](https://github.com/GlobalFishingWatch/gfwr#authorization) of the README. Did you do that?

Hey @tclavelle — just following up on this as I had a colleague who was having issues getting the GFW token in their .Renviron file to work. It looks like if you name the token as `"GFW_token"` (with quotations per the [Authorisation section](https://github.com/GlobalFishingWatch/gfwr#authorization)), `Sys.getenv` doesn't find it, and calling the created `key` objects just gives an empty vector: (`[1] ""`). 

Tokens named without quotations work fine (`GFW_TOKEN = "PASTE_YOUR_TOKEN_HERE"`)

I've only tested this by editing the .Renviron file for my current project (e.g. `usethis::edit_r_environ("project")`, but guessing this issue applies to both global and local edits. Have not made a pull request in case I'm missing something obvious, so feel free to let me know either way!

**Pull request merged**
